### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by mipastgt** [eclipse-efx/efxclipse-drift#16]
Could you please provide some build instructions for the project, especially for the native part? I tried a build yesterday with the Java11 branch and after a long time of fiddling I got the sample running. The initial setup works but as soon as I switch to the triangles and restart the animation, Java crashes completely. But before I write a bug report about this I would like to make sure that my build procedure was as intended. (This was on a MacBook Pro with Retina display and macOS 10.14.6)

**Comment by tomsontom** [comment]
You are right we should have them documented excliplictly - for the time being you can look into our travis-setup files who contain the build

**Comment by redrezo** [comment]
See [Development](https://github.com/eclipse-efx/efxclipse-drift/blob/master/Development.md)
