### ISSUE TITLE
Clean up debugging output

### ISSUE THREAD

**Issue by redrezo** [eclipse-efx/efxclipse-drift#27]
There are still some debug output left

**Comment by ReikaKalseki** [comment]
In particular, [J] [DEBUG] *downloaded 1 => <some hex address> printed either every frame or on some other rapid cycle. The others are all one-time, but that one rapidly generates an insane quantity of output.

**Comment by redrezo** [comment]
Yeah this is the log of the main memory mode when a frame is downloaded to memory
which occurs for every frame rendered
I think i will introduce a logging Service where you could consume that stuff and print it yourself if wanted
