### ISSUE TITLE
DriftFXSurface size seems not properly manipulatable

### ISSUE THREAD

**Issue by ReikaKalseki** [eclipse-efx/efxclipse-drift#30]
I have a DriftFX surface in my project that I am trying to get to be *exactly* 800x800. The node itself lacks a setWidth/Height or modifiable property for the same, nor any "pref size" ability, so I tried wrapping it in a Pane whose pref size I set to 800x800. I got a 100x100 surface instead. I tried a 6400x6400 size, in case of some factor of 8 scale...and I got 100x100 again. In fact, no matter what I do, I seem to get 100x100 unless the DFX surface is "loose" inside a "freeform sized" node (eg borderpane center like before), which also removes my ability to pick a size.

**Comment by tomsontom** [comment]
It's the job of the layout-container to choose assign a size to an element. If you want a fixed size Node you do it like this
```java
....
surface.setMinSize(800,800);
surface.setPrefSize(800,800);
surface.setMaxSize(800,800);
```
the parent container then calls min/pref/max(Height/Width) and calls resizeRelocate() to position your node in the parent space.

**Comment by ReikaKalseki** [comment]
Like I said in the first post, there *is* no `setPrefSize` (or min or max for that matter) on the DriftFXSurface.

**Comment by tomsontom** [comment]
100x100 is the default value hardcoded - we should add a way to set the from the outside - a workround for the time is to wrap it in eg an AnchorPane and set the Size there to 800x800

**Comment by ReikaKalseki** [comment]
I tried wrapping it in an AnchorPane and still got a 100x100 size. I am going to try the new build instead.

**Comment by ReikaKalseki** [comment]
OK, to get it to work I had to use the AnchorPane wrapper *and* setPrefSize.
