### ISSUE TITLE
Mouse movement redirection? Keyboard?

### ISSUE THREAD

**Issue by eix128** [eclipse-efx/efxclipse-drift#38]
Hi , i Want to redirect mouse an keyboard actions to my 3D engine.İs This library supports that? So i can rotate 3D objects.Synchronizing mouse movements ? How to do it with this library ?

**Comment by redrezo** [comment]
drift allows you to render the output of your 3D engine within javafx. you have to do the input redirection yourself

**Comment by redrezo** [comment]
fyi: The lwjgl sample (https://github.com/BestSolution-at/efxclipse-drift-samples/) uses the mouse input to rotate a 3d object. It simply installs a javafx mouse listener.
