### ISSUE TITLE
Incidental Crash

### ISSUE THREAD

**Issue by dhatbj** [eclipse-efx/efxclipse-drift#4]
First, thank you for your great works!

I'm developing a JavaFX player. The native C code update Texture to show video frames in a render loop. The App will crash incidentally. 

Process:               java [10637]
Path:                  /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/bin/java
Identifier:            java
Version:               1.0 (1.0)
Code Type:             X86-64 (Native)
Parent Process:        java [1158]
Responsible:           java [10637]
User ID:               501

Date/Time:             2019-02-15 15:00:46.836 +0800
OS Version:            Mac OS X 10.13.6 (17G65)

System Integrity Protection: enabled

Crashed Thread:        31  Java: Thread-7

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 31 Crashed:: Java: Thread-7
0   libsystem_kernel.dylib        	0x00007fff7dc74b66 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff7de3f080 pthread_kill + 333
2   libsystem_c.dylib             	0x00007fff7dbd01ae abort + 127
3   libjvm.dylib                  	0x000000010f739fd3 os::abort(bool) + 25
4   libjvm.dylib                  	0x000000010f862132 VMError::report_and_die() + 2304
5   libjvm.dylib                  	0x000000010f73bc16 JVM_handle_bsd_signal + 1131
6   libjvm.dylib                  	0x000000010f737e53 signalHandler(int, __siginfo*, void*) + 47
7   libsystem_platform.dylib      	0x00007fff7de32f5a _sigtramp + 26
8   ???                           	000000000000000000 0 + 0
9   com.apple.opengl              	0x00007fff601e168c CGLTexImageIOSurface2D + 175
10  libdriftfx.dylib              	0x000000012b85bc9d driftfx::internal::prism::es2::cgl::CGLES2PrismBridge::ConnectTextureToIOSurface(int, int, int, long) + 2317
11  libdriftfx.dylib              	0x000000012b85dbec Java_org_eclipse_fx_drift_internal_NativeAPI_nES2ConnectTextureToIOSurface + 860
12  ???                           	0x0000000116895667 0 + 4673066599
13  ???                           	0x0000000116884d00 0 + 4672998656
14  ???                           	0x0000000116884d00 0 + 4672998656
15  ???                           	0x00000001171e0814 0 + 4682811412
16  ???                           	0x00000001168852bd 0 + 4673000125
17  ???                           	0x0000000116885302 0 + 4673000194
18  ???                           	0x000000011687d7a7 0 + 4672968615
19  libjvm.dylib                  	0x000000010f59c9aa JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) + 1710
20  libjvm.dylib                  	0x000000010f59d14e JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*) + 356
21  libjvm.dylib                  	0x000000010f59d2fa JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*) + 74
22  libjvm.dylib                  	0x000000010f5f7ae5 thread_entry(JavaThread*, Thread*) + 124
23  libjvm.dylib                  	0x000000010f81bdef JavaThread::thread_main_inner() + 155
24  libjvm.dylib                  	0x000000010f81d4ea JavaThread::run() + 450
25  libjvm.dylib                  	0x000000010f73a83a java_start(Thread*) + 246
26  libsystem_pthread.dylib       	0x00007fff7de3c661 _pthread_body + 340
27  libsystem_pthread.dylib       	0x00007fff7de3c50d _pthread_start + 377
28  libsystem_pthread.dylib       	0x00007fff7de3bbf9 thread_start + 13

Thread 31 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007000115b3000  rcx: 0x00007000115b1378  rdx: 0x0000000000000000
  rdi: 0x0000000000012283  rsi: 0x0000000000000006  rbp: 0x00007000115b13b0  rsp: 0x00007000115b1378
   r8: 0x00007fffb6609f78   r9: 0x0000000000000040  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000012283  r13: 0x0000000000001908  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff7dc74b66  rfl: 0x0000000000000206  cr2: 0x00007fffb6608168
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

**Comment by tomsontom** [comment]
What graphic card is your Mac? @redrezo  any idea what might the reason for the crash?

**Comment by dhatbj** [comment]
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Graphic card: Intel Iris Plus Graphics 640 1536 MB

**Comment by tomsontom** [comment]
Is your work opensource, so that we can try to reproduce it locally?

**Comment by dhatbj** [comment]
No, my player is not open source, It is under developing now.

**Comment by dhatbj** [comment]
When a 60fps video file is played, the crash must present.
