### ISSUE TITLE
Any chance you will support an lwjgl FBO or context?

### ISSUE THREAD

**Issue by xGnoSiSx** [eclipse-efx/efxclipse-drift#8]
In Lwjgl and other similar frameworks we already have FBOs that were created and rendered.

Would it be difficult to add support to pass the relevant lwjgl object to your lib.

Of course those frameworks create their own main window. I'm not asking for complete integration.

[lwjgl](https://github.com/LWJGL/lwjgl3)

**Comment by redrezo** [comment]
The 1.0.0.rc0 Release allows you to use your own OpenGL context, but you still have to draw to the texture which is manage by drift, you can use it in your fbo or blit your final Image to it
